### ISSUE TITLE
Optimize with Adam

### ISSUE THREAD

**Issue by DeepBlockDeepak** [DeepBlockDeepak/my-neural-network#14]
## TODO:
- [x] add hyperparameters beta1, beta2, and epsilon to `NeuralNetworkConfig`.
- [x] encap initialization of first and second moment variables
- [x] change current parameter updating to use Adam instead of SGD.
- [x] use time step t and update it

See https://stackoverflow.com/questions/54247393/adam-in-tensorflow-where-does-moment-estimates-happen
